# Generated by Django 5.0.6 on 2024-09-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('pharmacy', 'Pharmacy'), ('DRIVERS', 'Drivers'), ('company', 'Company')], default='pharmacy', max_length=50),
        ),
    ]
