# Generated by Django 5.0.6 on 2024-09-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locals',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('pharmacy', 'Pharmacy'), ('DRIVERS', 'Drivers'), ('company', 'Company')], max_length=50),
        ),
    ]
