# Generated by Django 5.0.6 on 2024-09-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_locals_alter_user_id_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
