# Generated by Django 5.0.6 on 2024-09-04 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size_order',
            name='id_pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacies.pharmacy'),
            preserve_default=False,
        ),
    ]
