# Generated by Django 5.0.6 on 2024-09-12 09:21

import django.contrib.auth.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_size_order_id_pharmacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='pharmacy',
            managers=[
                ('pharmacy', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='account',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='locals',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='name',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
