# Generated by Django 5.0.6 on 2024-09-12 09:50

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_alter_pharmacy_options_alter_pharmacy_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={},
        ),
        migrations.AlterModelManagers(
            name='pharmacy',
            managers=[
                ('pharmacy', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
